use_frameworks!

target 'MXSelectedCollectionView_Example' do
  pod 'MXSelectedCollectionView', :path => '../'

  target 'MXSelectedCollectionView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
